apiVersion: apps/v1
kind: Deployment
metadata:
  name: phasenet-api
  labels:
    app: phasenet
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: phasenet
  template:
    metadata:
      labels:
        app: phasenet
    spec:
      containers:
        - name: phasenet
          image: zhuwq0/phasenet-api:1.0
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "800m"
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 600
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: phasenet-api
spec:
  selector:
    app: phasenet
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
  # type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmma-api
  labels:
    app: gmma
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: gmma
  template:
    metadata:
      labels:
        app: gmma
    spec:
      containers:
        - name: gmma
          image: zhuwq0/gmma-api:1.0
          ports:
            - containerPort: 8001
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: gmma-api
spec:
  selector:
    app: gmma
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer
  # type: NodePort
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: quakeflow-spark
#   labels:
#     app: spark
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: spark
#   template:
#     metadata:
#       labels:
#         app: spark
#     spec:
#       containers:
#         - name: spark
#           image: zhuwq0/quakeflow-spark:1.0
#           imagePullPolicy: Always
#           resources:
#             requests:
#               cpu: "250m"
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: quakeflow-waveform
#   labels:
#     app: waveform
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: waveform
#   template:
#     metadata:
#       labels:
#         app: waveform
#     spec:
#       containers:
#         - name: waveform
#           image: zhuwq0/quakeflow-waveform:1.0
#           imagePullPolicy: Always
#           resources:
#             requests:
#               cpu: "250m"
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: quakeflow-ui
#   labels:
#     app: quakeflow-ui
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: quakeflow-ui
#   template:
#     metadata:
#       labels:
#         app: quakeflow-ui
#     spec:
#       containers:
#         - name: quakeflow-ui
#           image: zhuwq0/quakeflow-ui:1.0
#           ports:
#             - containerPort: 8005
#           imagePullPolicy: Always
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: quakeflow-ui
# spec:
#   selector:
#     app: ui
#   ports:
#     - protocol: TCP
#       port: 8005
#       targetPort: 8005
# ---

